/**
 * Feed API - "The Feed" Social Content
 * Functions for user-generated content, reactions, and comments
 */

import { ENDPOINTS } from '@/constants/api';
import { apiClient } from './client';

// Types
export interface FeedUser {
  _id: string;
  name: string;
  email?: string;
  imageUri?: string | null;
}

export interface PostStats {
  loveCount: number;
  respectCount: number;
  commentCount: number;
  shareCount: number;
  viewCount: number;
  saveCount: number;
}

export interface FeedPost {
  _id: string;
  userId: string;
  user?: FeedUser;
  mediaType: 'video' | 'image' | 'carousel';
  bunnyVideoId?: string;
  hlsUrl?: string;
  thumbnailUrl?: string;
  imageUrls?: string[];
  // Signed URLs for video playback (generated by backend)
  signedHlsUrl?: string;
  signedMp4Url?: string;
  signedThumbnailUrl?: string;
  caption?: string;
  sportTypes?: string[];
  tricks?: string[];
  location?: string;
  duration?: number; // seconds (max 180)
  aspectRatio?: string;
  stats: PostStats;
  engagement?: {
    completionRate: number;
    rewatchRate: number;
    skipRate: number;
  };
  visibility: 'public' | 'homies' | 'private';
  status: 'processing' | 'published' | 'removed';
  userReactions?: ('love' | 'respect')[];
  saved?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Comment {
  _id: string;
  postId: string;
  userId: string;
  user?: FeedUser;
  parentCommentId?: string | null;
  content: string;
  loveCount: number;
  replyCount: number;
  loved?: boolean;
  status: 'active' | 'deleted';
  createdAt: string;
}

export interface FeedResponse {
  posts: FeedPost[];
  pagination: {
    page: number;
    limit: number;
    hasMore?: boolean;
    total?: number;
    pages?: number;
  };
}

export interface CommentsResponse {
  comments: Comment[];
  pagination: {
    page: number;
    limit: number;
    hasMore?: boolean;
  };
}

// =============================================
// FEED ENDPOINTS
// =============================================

/**
 * Get algorithmic feed (homies prioritized, recent first)
 */
export async function getFeed(
  params: { page?: number; limit?: number; sort?: 'recent' | 'trending' | 'algorithmic' } = {},
): Promise<FeedResponse> {
  try {
    const queryParams = new URLSearchParams();
    if (params.page) queryParams.append('page', params.page.toString());
    if (params.limit) queryParams.append('limit', params.limit.toString());
    // Default to 'recent' sort with homies prioritization
    queryParams.append('sort', params.sort || 'recent');
    queryParams.append('prioritizeHomies', 'true');

    const queryString = queryParams.toString();
    const endpoint = queryString ? `${ENDPOINTS.feed.list}?${queryString}` : ENDPOINTS.feed.list;

    const response = await apiClient.get<FeedResponse>(endpoint);
    return response;
  } catch (_error) {
    return { posts: [], pagination: { page: 1, limit: 20, hasMore: false } };
  }
}

/**
 * Get trending posts
 */
export async function getTrending(
  params: { page?: number; limit?: number; sport?: string } = {},
): Promise<FeedResponse> {
  try {
    const queryParams = new URLSearchParams();
    if (params.page) queryParams.append('page', params.page.toString());
    if (params.limit) queryParams.append('limit', params.limit.toString());
    if (params.sport && params.sport !== 'all') queryParams.append('sport', params.sport);

    const queryString = queryParams.toString();
    const endpoint = queryString
      ? `${ENDPOINTS.feed.trending}?${queryString}`
      : ENDPOINTS.feed.trending;

    const response = await apiClient.get<FeedResponse>(endpoint, { skipAuth: true });
    return response;
  } catch (_error) {
    return { posts: [], pagination: { page: 1, limit: 20 } };
  }
}

/**
 * Get user's posts
 */
export async function getUserPosts(
  userId: string,
  params: { page?: number; limit?: number } = {},
): Promise<FeedResponse> {
  try {
    const queryParams = new URLSearchParams();
    if (params.page) queryParams.append('page', params.page.toString());
    if (params.limit) queryParams.append('limit', params.limit.toString());

    const queryString = queryParams.toString();
    const endpoint = queryString
      ? `${ENDPOINTS.feed.userPosts(userId)}?${queryString}`
      : ENDPOINTS.feed.userPosts(userId);

    const response = await apiClient.get<FeedResponse>(endpoint);
    return response;
  } catch (_error) {
    return { posts: [], pagination: { page: 1, limit: 20, total: 0, pages: 0 } };
  }
}

/**
 * Get sport-specific feed
 */
export async function getFeedBySport(
  sportType: string,
  params: { page?: number; limit?: number } = {},
): Promise<FeedResponse> {
  try {
    const queryParams = new URLSearchParams();
    if (params.page) queryParams.append('page', params.page.toString());
    if (params.limit) queryParams.append('limit', params.limit.toString());

    const queryString = queryParams.toString();
    const endpoint = queryString
      ? `${ENDPOINTS.feed.bySport(sportType)}?${queryString}`
      : ENDPOINTS.feed.bySport(sportType);

    const response = await apiClient.get<FeedResponse>(endpoint, { skipAuth: true });
    return response;
  } catch (_error) {
    return { posts: [], pagination: { page: 1, limit: 20 } };
  }
}

/**
 * Get single post details
 */
export async function getPost(postId: string): Promise<FeedPost | null> {
  try {
    const response = await apiClient.get<FeedPost>(ENDPOINTS.feed.post(postId));
    return response;
  } catch (_error) {
    return null;
  }
}

/**
 * Get saved posts
 */
export async function getSavedPosts(
  params: { page?: number; limit?: number } = {},
): Promise<FeedResponse> {
  try {
    const queryParams = new URLSearchParams();
    if (params.page) queryParams.append('page', params.page.toString());
    if (params.limit) queryParams.append('limit', params.limit.toString());

    const queryString = queryParams.toString();
    const endpoint = queryString ? `${ENDPOINTS.feed.saved}?${queryString}` : ENDPOINTS.feed.saved;

    const response = await apiClient.get<FeedResponse>(endpoint);
    return response;
  } catch (_error) {
    return { posts: [], pagination: { page: 1, limit: 20 } };
  }
}

// =============================================
// POST CRUD
// =============================================

export interface CreatePostData {
  mediaType: 'video' | 'image' | 'carousel';
  bunnyVideoId?: string;
  hlsUrl?: string;
  thumbnailUrl?: string;
  imageUrls?: string[];
  caption?: string;
  sportTypes?: string[];
  tricks?: string[];
  location?: string;
  duration?: number;
  aspectRatio?: string;
  visibility?: 'public' | 'homies' | 'private';
}

/**
 * Create new post
 */
export async function createPost(data: CreatePostData): Promise<FeedPost | null> {
  try {
    const response = await apiClient.post<FeedPost>(ENDPOINTS.feed.create, data);
    return response;
  } catch (_error) {
    return null;
  }
}

/**
 * Update post (caption, visibility, sportTypes, tricks)
 */
export async function updatePost(
  postId: string,
  data: Partial<Pick<FeedPost, 'caption' | 'visibility' | 'sportTypes' | 'tricks'>>,
): Promise<FeedPost | null> {
  try {
    const response = await apiClient.put<FeedPost>(ENDPOINTS.feed.update(postId), data);
    return response;
  } catch (_error) {
    return null;
  }
}

/**
 * Delete post
 */
export async function deletePost(postId: string): Promise<boolean> {
  try {
    await apiClient.delete(ENDPOINTS.feed.delete(postId));
    return true;
  } catch (_error) {
    return false;
  }
}

// =============================================
// REACTIONS
// =============================================

/**
 * Add reaction (love or respect)
 */
export async function addReaction(
  postId: string,
  type: 'love' | 'respect',
): Promise<{ loveCount: number; respectCount: number } | null> {
  try {
    const response = await apiClient.post<{
      message: string;
      loveCount: number;
      respectCount: number;
    }>(ENDPOINTS.feed.reaction(postId), { type });
    return { loveCount: response.loveCount, respectCount: response.respectCount };
  } catch (_error) {
    return null;
  }
}

/**
 * Remove reaction
 */
export async function removeReaction(
  postId: string,
  type: 'love' | 'respect',
): Promise<{ loveCount: number; respectCount: number } | null> {
  try {
    const response = await apiClient.delete<{
      message: string;
      loveCount: number;
      respectCount: number;
    }>(ENDPOINTS.feed.removeReaction(postId, type));
    return { loveCount: response.loveCount, respectCount: response.respectCount };
  } catch (_error) {
    return null;
  }
}

// =============================================
// COMMENTS
// =============================================

/**
 * Get comments for a post
 */
export async function getComments(
  postId: string,
  params: { page?: number; limit?: number } = {},
): Promise<CommentsResponse> {
  try {
    const queryParams = new URLSearchParams();
    if (params.page) queryParams.append('page', params.page.toString());
    if (params.limit) queryParams.append('limit', params.limit.toString());

    const queryString = queryParams.toString();
    const endpoint = queryString
      ? `${ENDPOINTS.feed.comments(postId)}?${queryString}`
      : ENDPOINTS.feed.comments(postId);

    const response = await apiClient.get<CommentsResponse>(endpoint, { skipAuth: true });
    return response;
  } catch (_error) {
    return { comments: [], pagination: { page: 1, limit: 20 } };
  }
}

/**
 * Add comment
 */
export async function addComment(
  postId: string,
  content: string,
  parentCommentId?: string,
): Promise<Comment | null> {
  try {
    const response = await apiClient.post<Comment>(ENDPOINTS.feed.comment(postId), {
      content,
      parentCommentId,
    });
    return response;
  } catch (_error) {
    return null;
  }
}

/**
 * Delete comment
 */
export async function deleteComment(postId: string, commentId: string): Promise<boolean> {
  try {
    await apiClient.delete(ENDPOINTS.feed.deleteComment(postId, commentId));
    return true;
  } catch (_error) {
    return false;
  }
}

/**
 * Get replies to a comment
 */
export async function getCommentReplies(
  postId: string,
  commentId: string,
  params: { page?: number; limit?: number } = {},
): Promise<{ replies: Comment[]; pagination: { page: number; limit: number; hasMore: boolean } }> {
  try {
    const queryParams = new URLSearchParams();
    if (params.page) queryParams.append('page', params.page.toString());
    if (params.limit) queryParams.append('limit', params.limit.toString());

    const queryString = queryParams.toString();
    const endpoint = queryString
      ? `${ENDPOINTS.feed.commentReplies(postId, commentId)}?${queryString}`
      : ENDPOINTS.feed.commentReplies(postId, commentId);

    const response = await apiClient.get<{
      replies: Comment[];
      pagination: { page: number; limit: number; hasMore: boolean };
    }>(endpoint, { skipAuth: true });
    return response;
  } catch (_error) {
    return { replies: [], pagination: { page: 1, limit: 10, hasMore: false } };
  }
}

/**
 * Love/unlove a comment (toggle)
 */
export async function toggleCommentLove(
  postId: string,
  commentId: string,
): Promise<{ loved: boolean; loveCount: number } | null> {
  try {
    const response = await apiClient.post<{ loved: boolean; loveCount: number }>(
      ENDPOINTS.feed.loveComment(postId, commentId),
      {},
    );
    return response;
  } catch (_error) {
    return null;
  }
}

// =============================================
// OTHER
// =============================================

/**
 * Save/unsave post
 */
export async function toggleSavePost(postId: string, save: boolean): Promise<boolean> {
  try {
    await apiClient.post(ENDPOINTS.feed.save(postId), { save });
    return true;
  } catch (_error) {
    return false;
  }
}

/**
 * Track post view
 */
export async function trackPostView(
  postId: string,
  data?: { watchDuration?: number; completed?: boolean },
): Promise<boolean> {
  try {
    await apiClient.post(ENDPOINTS.feed.view(postId), data || {}, { skipAuth: true });
    return true;
  } catch (_error) {
    return false;
  }
}

/**
 * Report a post
 */
export async function reportPost(postId: string, reason: string): Promise<boolean> {
  try {
    await apiClient.post(ENDPOINTS.feed.report(postId), { reason });
    return true;
  } catch (_error) {
    return false;
  }
}

// =============================================
// HELPERS
// =============================================

/**
 * Format time ago string
 */
export function formatTimeAgo(dateString: string): string {
  const date = new Date(dateString);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffSecs = Math.floor(diffMs / 1000);
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);
  const diffWeeks = Math.floor(diffDays / 7);

  if (diffSecs < 60) return 'just now';
  if (diffMins < 60) return `${diffMins}m`;
  if (diffHours < 24) return `${diffHours}h`;
  if (diffDays < 7) return `${diffDays}d`;
  if (diffWeeks < 4) return `${diffWeeks}w`;
  return date.toLocaleDateString([], { month: 'short', day: 'numeric' });
}

/**
 * Format reaction count for display
 */
export function formatCount(count: number): string {
  if (count >= 1000000) {
    return `${(count / 1000000).toFixed(1)}M`;
  }
  if (count >= 1000) {
    return `${(count / 1000).toFixed(1)}K`;
  }
  return count.toString();
}
